### ISSUE TITLE
Sticky position one the left column

### ISSUE THREAD

**Issue by PhanDangKhoa96** [Namchee/site#55]
It is not an issue at all, I just have an idea that it would be better that the left hand column is sticky when scrolling. So your personal information will always appear in the screen view :D

Something like this:
![image](https://github.com/user-attachments/assets/5f81fc86-4584-4296-9132-d0186adec356)

**Comment by Namchee** [comment]
Hi @PhanDangKhoa96, 

Thank you for posting an issue! I'm aware that the left column is no longer sticky compared to the previous version. However, the changes are expected as I'm still working on some style changes regarding to the website.

I'll temporarily close this issue for the time being. Stay tuned!
